<style>
    table a.cmd_url{
        background-color: transparent;
        display: block;
    }
</style>

<h4>Letzte &Uuml;berpr&uuml;fung : <?php echo $this->scan_date; ?></h4>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Beschreibung</th>
            <th>Url</th>
            <th style="width: 100px;">auf Seite (ID)</th>
            <th style="width: 20px;">&nbsp;</th>
        </tr>
    </thead>
    
    <tbody>
        <?php foreach($this->errorUrls as $url): ?>
        <tr>
            <td><?php echo $url["description"]; ?></td>
            <td><?php echo $url["url"]; ?></td>
            <td style="text-align: center;"><?php echo $url["page_id"]; ?></td>
            <td><a class="cmd_url" href="<?php echo $this->baseUrl . "?index=" . $url["page_id"] . "&obj=pageitems"; ?>"><i class="icon-share-alt"></i></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>